<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework 3</span></h1>


    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>
</div>
<div class="row">
    <a href="<?php echo $this->basePath('/post/add'); ?>" class="btn btn-primary">CREATE</a>
</div>

<div class="row">

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php if (count($posts)>0): ?>
            <?php foreach ($posts as $post):?>
                <tr class="table-active">
                    <th><?php echo $post->getId(); ?></th>
                    <td><?php echo $post->getTitle();?></td>
                    <td><?php echo $post->getDescription();?></td>
                    <td><?php echo $post->getCategory();?></td>
                    <td><a href="<?php echo $this->url('post', ['action' => 'view', 'id' => $post->getId()]);?>" class="label label-primary">View</a></td>
                    <td><a href="<?php echo $this->url('post', ['action' => 'edit', 'id' => $post->getId()]);?>" class="label label-default">Update</a></td>
                    <td><a href="<?php echo $this->url('post', ['action' => 'delete', 'id' => $post->getId()]);?>" class="label label-danger">Delete</a></td>
                </tr>
            <?php endforeach; ?>
          <?php else: ?>
                <tr>
                    <td> No records Founds ! </td>
                </tr>
        <?php endif ?>
        </tbody>
    </table>

</div>
